import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"00_ケース検証運用（共通）","description":"","frontmatter":{},"headers":[],"relativePath":"01_学習本線/ケース検証/00_ケース検証運用（共通）.md","filePath":"01_学習本線/ケース検証/00_ケース検証運用（共通）.md","lastUpdated":1779862035000}');
const _sfc_main = { name: "01_学習本線/ケース検証/00_ケース検証運用（共通）.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="_00-ケース検証運用-共通" tabindex="-1">00_ケース検証運用（共通） <a class="header-anchor" href="#_00-ケース検証運用-共通" aria-label="Permalink to &quot;00_ケース検証運用（共通）&quot;">​</a></h1><h2 id="目的" tabindex="-1">目的 <a class="header-anchor" href="#目的" aria-label="Permalink to &quot;目的&quot;">​</a></h2><ul><li>ここに貼られた内容を、まずケース検証ファイルとして形成して履歴化する。</li><li>その後、再利用価値のある原理だけを各カテゴリ本線へ戻す。</li><li>「正解集」ではなく「条件 -&gt; 出力 -&gt; 採用理由」の検証ルートを残す。</li></ul><h2 id="基本フロー-固定" tabindex="-1">基本フロー（固定） <a class="header-anchor" href="#基本フロー-固定" aria-label="Permalink to &quot;基本フロー（固定）&quot;">​</a></h2><ol><li>学習寄りの単独検証は <code>01_学習本線/ケース検証</code> に記録する（単一議題は1ケース1ファイル、複数議題回は1ファイル内で <code>ケース1 / ケース2 / ...</code> に分割する）<br> 案件で発生したケースは <code>02_案件・制作/ケース検証</code> で受ける</li><li>各ケースごとに現象/条件/出力/採用理由を独立させて確定する</li><li>各カテゴリ本線（HTML・CSS / JS / React / TypeScript）へ必要知識だけ反映する（日時ログ追記ではなく、カテゴリ見出しへ一般化して統合する）</li><li>ケースファイル末尾の「本線への反映先」を更新し、反映内容を集約する</li></ol><h2 id="ファイル命名" tabindex="-1">ファイル命名 <a class="header-anchor" href="#ファイル命名" aria-label="Permalink to &quot;ファイル命名&quot;">​</a></h2><ul><li><code>00</code>: 運用ルール専用（このファイル）</li><li><code>01</code> 以降: <code>NN_ケース_&lt;短いケース名&gt;.md</code></li><li>例: <ul><li><code>01_ケース_Blogカード画像_レンダリング挙動.md</code></li><li><code>02_ケース_aria-hiddenとモーダル状態同期.md</code></li></ul></li></ul><h2 id="_1ファイルに書く範囲" tabindex="-1">1ファイルに書く範囲 <a class="header-anchor" href="#_1ファイルに書く範囲" aria-label="Permalink to &quot;1ファイルに書く範囲&quot;">​</a></h2><ul><li>単一議題の回は、1ファイル1状況に限定する。</li><li>複数議題が混在する回は、1ファイル内で <code>ケース1 / ケース2 / ...</code> に分ける。</li><li>複数ケース運用でも、各ケースの条件・結論は混線させない。</li><li>「たまたま直った」ケースも残す（再現条件を失わないため）。</li></ul><h2 id="解説密度-固定" tabindex="-1">解説密度（固定） <a class="header-anchor" href="#解説密度-固定" aria-label="Permalink to &quot;解説密度（固定）&quot;">​</a></h2><ul><li>短い要約だけで終えず、途中判断（どこで迷ったか / 何を除外したか）を残す。</li><li>多少雑多でもよいので、後から「なぜそう判断したか」を追える記録を優先する。</li><li>最終結論だけでなく、条件 / 理由 / 例外の3点を最低限残す。</li></ul><h2 id="本線反映のルール" tabindex="-1">本線反映のルール <a class="header-anchor" href="#本線反映のルール" aria-label="Permalink to &quot;本線反映のルール&quot;">​</a></h2><ul><li>本線/実務側への反映は「日時のケース補足を追加する」方式ではなく、既存カテゴリへ統合して一般化知識として残す。</li><li>既存カテゴリで収まらない場合は、2階層目以降で新規カテゴリ（フォルダ/ファイル/見出し）を追加してよい。</li><li>ケース反映の要約は、反映先ではなくケースファイル末尾の「本線への反映先」に集約する。</li></ul><h2 id="記録テンプレ" tabindex="-1">記録テンプレ <a class="header-anchor" href="#記録テンプレ" aria-label="Permalink to &quot;記録テンプレ&quot;">​</a></h2><div class="language-md vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">md</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-light-font-weight": "bold", "--shiki-dark": "#79B8FF", "--shiki-dark-font-weight": "bold" })}"># NN_ケース_テーマ</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-light-font-weight": "bold", "--shiki-dark": "#79B8FF", "--shiki-dark-font-weight": "bold" })}">## このページの扱い</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">-</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> 単一議題 or 複数議題（ケース分割）</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-light-font-weight": "bold", "--shiki-dark": "#79B8FF", "--shiki-dark-font-weight": "bold" })}">## ケース1_お題名</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-light-font-weight": "bold", "--shiki-dark": "#79B8FF", "--shiki-dark-font-weight": "bold" })}">### 現象</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">-</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> 何が崩れたか（見た目 / 挙動）</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-light-font-weight": "bold", "--shiki-dark": "#79B8FF", "--shiki-dark-font-weight": "bold" })}">### 前提条件</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">-</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> HTML/CSS条件</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">-</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> JS条件</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-light-font-weight": "bold", "--shiki-dark": "#79B8FF", "--shiki-dark-font-weight": "bold" })}">### 仮説</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">-</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> どの条件が効いているか</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-light-font-weight": "bold", "--shiki-dark": "#79B8FF", "--shiki-dark-font-weight": "bold" })}">### 検証ログ（1回に1条件）</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">1.</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> 変更した条件</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">2.</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> 出力</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">3.</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> 判定</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-light-font-weight": "bold", "--shiki-dark": "#79B8FF", "--shiki-dark-font-weight": "bold" })}">### 採用した形</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">-</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> 最終実装</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">-</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> 採用理由（条件 / 理由 / 例外）</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-light-font-weight": "bold", "--shiki-dark": "#79B8FF", "--shiki-dark-font-weight": "bold" })}">### 見送った形</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">-</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> 不採用理由</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-light-font-weight": "bold", "--shiki-dark": "#79B8FF", "--shiki-dark-font-weight": "bold" })}">## ケース2_お題名（必要時のみ）</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">-</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> 同じ形式で記録</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-light-font-weight": "bold", "--shiki-dark": "#79B8FF", "--shiki-dark-font-weight": "bold" })}">## 本線への反映先</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#E36209", "--shiki-dark": "#FFAB70" })}">-</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> どのカテゴリに何を戻したか</span></span></code></pre></div><h2 id="混在ui-js×html-css-の扱い" tabindex="-1">混在UI（JS×HTML/CSS）の扱い <a class="header-anchor" href="#混在ui-js×html-css-の扱い" aria-label="Permalink to &quot;混在UI（JS×HTML/CSS）の扱い&quot;">​</a></h2><ul><li>主因を即断しづらい混在ケースは、このフォルダで管理する。</li><li>主因が明確な場合のみ、カテゴリ側ケースへ置く。 <ul><li>見た目主因: HTML・CSS側</li><li>挙動主因: JS側</li></ul></li><li>ただし「主ファイルは1本」に固定し、他側は参照リンクと要点だけ残す。</li></ul><h2 id="ケース分析から本線へ戻す手順" tabindex="-1">ケース分析から本線へ戻す手順 <a class="header-anchor" href="#ケース分析から本線へ戻す手順" aria-label="Permalink to &quot;ケース分析から本線へ戻す手順&quot;">​</a></h2><ol><li>ケース側で結論まで検証する</li><li>再利用原理だけ抽出する</li><li>抽出原理を該当カテゴリ本線に追記する</li><li>ケースファイル末尾の「本線への反映先」に反映結果を追記する</li><li>ケース本文は履歴として残し続ける</li></ol><h2 id="既存ケース-学習側" tabindex="-1">既存ケース（学習側） <a class="header-anchor" href="#既存ケース-学習側" aria-label="Permalink to &quot;既存ケース（学習側）&quot;">​</a></h2><ul><li><p><a href="./02_ケース_Blog一覧_SP基準設計と余白責務">02_ケース_Blog一覧_SP基準設計と余白責務</a></p></li><li><p><a href="./03_ケース_混在ログ整理とBlog詳細実装判断">03_ケース_混在ログ整理とBlog詳細実装判断</a></p></li><li><p><a href="./04_ケース_Blog詳細とPortfolio実装判断（混在ログ）">04_ケース_Blog詳細とPortfolio実装判断（混在ログ）</a></p></li><li><p><a href="./05_ケース_地図ピン配置と連絡先セマンティック判断（混在ログ）">05_ケース_地図ピン配置と連絡先セマンティック判断（混在ログ）</a></p></li><li><p><a href="./06_ケース_FAQコンポーネント化とページ責務分離">06_ケース_FAQコンポーネント化とページ責務分離</a></p></li><li><p><a href="./07_ケース_テキストノードと中央寄せ責務分離">07_ケース_テキストノードと中央寄せ責務分離</a></p></li><li><p><a href="./08_ケース_ノート可読性点検と画像背景整理">08_ケース_ノート可読性点検と画像背景整理</a></p></li></ul><h2 id="移管済みケース-案件側" tabindex="-1">移管済みケース（案件側） <a class="header-anchor" href="#移管済みケース-案件側" aria-label="Permalink to &quot;移管済みケース（案件側）&quot;">​</a></h2><ul><li><a href="./../../02_案件・制作/ケース検証/01_ケース_Blogカード画像_レンダリング挙動">01_ケース_Blogカード画像_レンダリング挙動</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("01_学習本線/ケース検証/00_ケース検証運用（共通）.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const _00____________ = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  _00____________ as default
};
