import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"01_ボックスとdisplay","description":"","frontmatter":{},"headers":[],"relativePath":"01_学習本線/HTML・CSS/01_ボックスとdisplay.md","filePath":"01_学習本線/HTML・CSS/01_ボックスとdisplay.md","lastUpdated":1780059290000}');
const _sfc_main = { name: "01_学習本線/HTML・CSS/01_ボックスとdisplay.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="_01-ボックスとdisplay" tabindex="-1">01_ボックスとdisplay <a class="header-anchor" href="#_01-ボックスとdisplay" aria-label="Permalink to &quot;01_ボックスとdisplay&quot;">​</a></h1><h2 id="目的" tabindex="-1">目的 <a class="header-anchor" href="#目的" aria-label="Permalink to &quot;目的&quot;">​</a></h2><ul><li>「背景色がどこに付くか」「なぜその大きさになるか」を、<code>display</code> とボックス生成の観点で説明できる状態にする。</li></ul><h2 id="ルール" tabindex="-1">ルール <a class="header-anchor" href="#ルール" aria-label="Permalink to &quot;ルール&quot;">​</a></h2><ul><li>画面に出る対象は、<code>DOM</code> と <code>CSSOM</code> を合成した結果（レンダーツリー）で決まる（<a href="./../../03_雑記/知識辞書（試運用）/02_単語カード/状態変化">状態変化</a>）。</li><li><code>display</code> は「どの種類のボックスを生成するか」に関与する。</li><li>文字は <a href="./../../03_雑記/知識辞書（試運用）/02_単語カード/テキストノード">テキストノード</a> として扱われ、指定反映は <a href="./../../03_雑記/知識辞書（試運用）/02_単語カード/CSS適用境界">CSS適用境界</a> を分けて見る。</li><li><code>box-sizing</code> は「生成されたボックスのサイズ計算ルール」を決める。</li><li>つまり、<code>display</code> と <code>box-sizing</code> は役割が違う。</li></ul><h3 id="ボックスとボックスモデルの区別" tabindex="-1">ボックスとボックスモデルの区別 <a class="header-anchor" href="#ボックスとボックスモデルの区別" aria-label="Permalink to &quot;ボックスとボックスモデルの区別&quot;">​</a></h3><table tabindex="0"><thead><tr><th>分類</th><th>何を決めるか</th><th>主な関連プロパティ</th></tr></thead><tbody><tr><td>表示ボックス</td><td>描画される領域そのもの</td><td><code>display</code>, <code>line-height</code>, <code>width</code>, <code>height</code></td></tr><tr><td>ボックスモデル</td><td><code>width</code>/<code>height</code> の解釈範囲</td><td><code>box-sizing</code>, <code>padding</code>, <code>border</code>, <code>margin</code></td></tr></tbody></table><h2 id="この章の扱い方-暗記より時系列" tabindex="-1">この章の扱い方（暗記より時系列） <a class="header-anchor" href="#この章の扱い方-暗記より時系列" aria-label="Permalink to &quot;この章の扱い方（暗記より時系列）&quot;">​</a></h2><ul><li>目的は「ボックスの種類を全部暗記すること」ではない。</li><li>目的は、ブラウザが描画する流れを時系列で追えるようにすること。</li></ul><div class="language-txt vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">txt</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>HTML要素がある</span></span>
<span class="line"><span>-&gt; CSSが当たる</span></span>
<span class="line"><span>-&gt; レイアウト上の箱が作られる</span></span>
<span class="line"><span>-&gt; 幅/高さ/余白/境界が決まる</span></span>
<span class="line"><span>-&gt; 配置される</span></span>
<span class="line"><span>-&gt; 背景/文字/画像が描画される</span></span></code></pre></div><p>実務では、詰まった時に必要な分だけ確認すればよい。 最初から全部を覚えるより、次を確認できる状態を優先する。</p><ul><li>どの要素の箱か</li><li>親は何か</li><li><code>display</code> は何か</li><li>幅/高さはどこから来ているか</li><li>余白は内側か外側か</li></ul><h2 id="ボックスモデルと描画ボックスの関係" tabindex="-1">ボックスモデルと描画ボックスの関係 <a class="header-anchor" href="#ボックスモデルと描画ボックスの関係" aria-label="Permalink to &quot;ボックスモデルと描画ボックスの関係&quot;">​</a></h2><p>同じ「ボックス」という言葉でも、見ている階層が違う。</p><h3 id="ボックスモデル" tabindex="-1">ボックスモデル <a class="header-anchor" href="#ボックスモデル" aria-label="Permalink to &quot;ボックスモデル&quot;">​</a></h3><ul><li><code>content / padding / border / margin</code> の調整対象</li><li><code>width</code>, <code>height</code>, <code>padding</code>, <code>border</code>, <code>margin</code>, <code>box-sizing</code> で直接触れる</li><li>つまり「CSSでサイズ・余白・枠線を調整するための箱」</li></ul><h3 id="描画ボックス-レイアウト上の箱" tabindex="-1">描画ボックス（レイアウト上の箱） <a class="header-anchor" href="#描画ボックス-レイアウト上の箱" aria-label="Permalink to &quot;描画ボックス（レイアウト上の箱）&quot;">​</a></h3><ul><li>ブラウザがレイアウト計算のために内部で作る箱</li><li>例: <code>block box</code>, <code>inline box</code>, <code>line box</code>, <code>flex item</code>, <code>grid item</code>, <code>anonymous box</code></li><li>CSSで名前を直接指定して操作する対象ではない <ul><li>例: <code>line-box: ...;</code> や <code>anonymous-box: ...;</code> のような指定はしない</li></ul></li></ul><p>補足:</p><ul><li>両者は別物だが無関係ではない。</li><li><code>display</code>, <code>position</code>, <code>line-height</code>, <code>font-size</code> などの指定で、内部で作られる描画ボックスの振る舞いは間接的に変わる。</li></ul><div class="language-txt vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">txt</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>CSSプロパティを指定する</span></span>
<span class="line"><span>-&gt; ブラウザ内部の描画ボックスの作られ方が変わる</span></span>
<span class="line"><span>-&gt; width / height / aspect-ratio / 余白の効き方が変わることがある</span></span></code></pre></div><h3 id="認識" tabindex="-1">認識 <a class="header-anchor" href="#認識" aria-label="Permalink to &quot;認識&quot;">​</a></h3><ul><li>ボックスモデル: CSSで直接調整する箱</li><li>描画ボックス: ブラウザが画面を作るために内部で生成する箱</li><li>ボックスモデルは暗記対象ではなく、描画の流れを追うための地図として使う。</li></ul><h2 id="例" tabindex="-1">例 <a class="header-anchor" href="#例" aria-label="Permalink to &quot;例&quot;">​</a></h2><div class="language-html vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">html</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">&lt;</span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">div</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> class</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;box box--a&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">&gt;A&lt;/</span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">div</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">&lt;</span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">span</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> class</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;box box--b&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">&gt;B&lt;/</span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">span</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">&gt;</span></span></code></pre></div><div class="language-css vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">css</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">.box</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  background</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">#dff2ff</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">.box--a</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  display</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">block</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  width</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">100</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">%</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">.box--b</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  display</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">inline</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><ul><li><code>block</code>: 既定では親幅方向に広がりやすい。</li><li><code>inline</code>: 横幅は内容依存。<code>width</code>/<code>height</code> は通常効かない（<a href="./../../03_雑記/知識辞書（試運用）/02_単語カード/置換要素">置換要素</a> を除く）。</li></ul><h3 id="a-タグに-aspect-ratio-が効きにくい例" tabindex="-1"><code>a</code> タグに <code>aspect-ratio</code> が効きにくい例 <a class="header-anchor" href="#a-タグに-aspect-ratio-が効きにくい例" aria-label="Permalink to &quot;\`a\` タグに \`aspect-ratio\` が効きにくい例&quot;">​</a></h3><div class="language-css vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">css</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">a</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  aspect-ratio</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">16</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> / </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">9</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><p><code>a</code> が既定の <code>inline</code> のままだと、行内文脈で扱われるため、期待した箱として効きにくいことがある。</p><div class="language-css vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">css</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">a</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  display</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">block</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  aspect-ratio</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">16</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> / </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">9</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><p>この変更は「ボックスモデルの調整」だけではなく、<code>display</code> によって描画ボックスの種類が変わることも含んでいる。</p><h2 id="初期認識メモ-確度" tabindex="-1">初期認識メモ（確度） <a class="header-anchor" href="#初期認識メモ-確度" aria-label="Permalink to &quot;初期認識メモ（確度）&quot;">​</a></h2><ul><li>確度: 高 <ul><li>「<code>display</code> の設定が先にあり、描画結果としてボックスが現れる」という時系列の見方。</li><li>「<code>display</code> と <code>box-sizing</code> は別問題」という切り分け。</li></ul></li><li>確度: 中 <ul><li>「コンテンツがなければ見える領域がほぼゼロに近づく」という観察（<code>height</code>/<code>padding</code> 指定で変わる）。</li></ul></li><li>確度: 要修正 <ul><li>「ブロック要素は自分だけでは領域を持たない」は不正確。<code>block</code> は内容がなくても、指定された <code>width</code>/<code>padding</code>/<code>border</code> で領域を持てる。</li></ul></li></ul><h2 id="判断基準" tabindex="-1">判断基準 <a class="header-anchor" href="#判断基準" aria-label="Permalink to &quot;判断基準&quot;">​</a></h2><ul><li>バグ時は次の順で切る（詳細度は最後）。</li></ul><ol><li>HTML構造と親子関係</li><li>レイアウト文脈（通常フロー / <code>flex</code> / <code>grid</code>）</li><li><code>display</code>（どのボックス種別か）</li><li><code>width</code> / <code>height</code>（どこで幅・高さが決まるか）</li><li><code>padding</code> / <code>margin</code> / <code>gap</code>（内側余白か外側余白か）</li><li><code>position</code> / <code>grid</code> / <code>flex</code> の配置指定</li><li>詳細度・上書き順（同強度なら後勝ち）</li></ol></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("01_学習本線/HTML・CSS/01_ボックスとdisplay.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const _01______display = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  _01______display as default
};
